### ISSUE TITLE
Auto variables and JSON not found

### ISSUE THREAD

**Issue by acherm** [diverse-project/varylatex#20]
I'm using `python3 main_server.py` 

When I upload the archive and want to automatically generate variation points I get this error:
```
127.0.0.1 - - [14/Sep/2020 18:16:10] "GET /static/js/auto_variables.js HTTP/1.1" 404 -
[2020-09-14 18:16:12,469] ERROR in app: Exception on /auto_variables [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mathieuacher/SANDBOX/varylatex/vary/views/project_files.py", line 61, in auto_variables
    add_graphics_variables(main_file_path)
  File "/home/mathieuacher/SANDBOX/varylatex/vary/model/files/tex_injection.py", line 120, in add_graphics_variables
    merge_configs(config_path, {"numbers": variables})
  File "/home/mathieuacher/SANDBOX/varylatex/vary/model/files/dictionnaries.py", line 9, in merge_configs
    with open(json_config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'vary/source/SPLC-AFM-synthesis/variables.json'
```

it seems that the automatic generation has been done eg looking at `practical.tex`
```
\begin{figure}
\centering
\includegraphics[scale=\getVal{scale_scalability_or.pdf}]{scalability_or.pdf}
\caption{\label{fig:scalability_or}Scalability of or-groups computation w.r.t the number of variables}
\end{figure}
````
but yes the JSON is missing... 
and also the "free config" mode or "constraints mode" is not then working (because of JSON missing I guess).

**Comment by FAMILIAR-project** [comment]
related to issue #22
